### ISSUE TITLE
Edge tf not ready 

### ISSUE THREAD

**Issue by HiranmayeeKadali** [OpenFogStack/enoki#1]
Hii I'm trying to running the experiment simple and I get a persistent 'edge tf not ready'. Will it take time to start the freD instance or should I change anything to run the experiment.
![WhatsApp Image 2024-05-02 at 12 43 18](https://github.com/OpenFogStack/enoki/assets/167014484/93da040a-0b21-48fb-a57a-7ceb40076a3d)

**Comment by pfandzelter** [comment]
Hi, can you provide the full output of the script? Maybe it encounters an error along the way

**Comment by HiranmayeeKadali** [comment]
[preparation.txt](https://github.com/OpenFogStack/enoki/files/15187873/preparation.txt)
[4_movingaverage-10-1-300-10-1-25-100-1-10-cloud-2.txt](https://github.com/OpenFogStack/enoki/files/15187877/4_movingaverage-10-1-300-10-1-25-100-1-10-cloud-2.txt)
Here it is

**Comment by pfandzelter** [comment]
Hi, it seems that the error is with your version of OpenSSL. Can you provide the output of `openssl version` on your computer?

**Comment by HiranmayeeKadali** [comment]
Hii Here it is,
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by pfandzelter** [comment]
Ok, I made the necessary changes to read the key file that is produced in newer versions of OpenSSL (PKCS#8 instead of PKCS#1). On macOS, OpenSSL 1.1.1 seems to be the default. You may need to recompile enoki for this, which should be part of the `prep-simple.sh` script. Make sure you have Go installed on your machine

**Comment by HiranmayeeKadali** [comment]
Thanks for the support and update. Will update if I face any more issues.

**Comment by HiranmayeeKadali** [comment]
Hii Again! I'm successful with the "simple" experiment. But for befaas and replication experiment, i get this 
[preparation.txt](https://github.com/OpenFogStack/enoki/files/15190615/preparation.txt)
Can you suggest if i'm missing something or should i change anything?:)

**Comment by pfandzelter** [comment]
Looks like Terraform is deploying to the `faasm-422113` project but `enoki-422018` is used for connecting the machine. Not sure what is causing this, looks like some configuration on your machine

**Comment by HiranmayeeKadali** [comment]
Hii @pfandzelter I have a small question, I'm trying to run the replication and scale experiments. 
For replication experiment, I can create a client instance because of the following error, "1mError waiting for instance to create: Quota 'N2_CPUS' exceeded.  Limit: 8.0" Can you advice any other to run this, I'm trying to contact the GCP service to increase the quota but no response yet. 
I can't find the prep_scale.sh file for scale experiment.
I'm trying to work with your work for my thesis work, your advice will be quite helpful.

**Comment by pfandzelter** [comment]
Hi, regarding the quota you can a) have GCP update your quota to 10 CPUs, b) use other cloud machine types (see `variables.tf`) so that the experiment is below this quota, or c) use your own servers if you have access to any, but that will require changing the setup scripts accordingly.

There is no `prep_scale.sh` as that uses the `prep.sh` script to prepare, see [`experiment-scale.py`](https://github.com/OpenFogStack/enoki/blob/1e6716ebde69d319aea3c8a10b94637aab85be5f/experiment-scale.py#L183)

**Comment by HiranmayeeKadali** [comment]
Hi, Thankyou so much for the advice, but I get file not found error for prep.sh.

ekadsre@ct-blade43:~/enoki$ ./experiment-scale.py
Preparing...
Output: output/output-scale/preparation.txt
Traceback (most recent call last):
  File "/home/ekadsre/enoki/./experiment-scale.py", line 183, in <module>
    subprocess.run(["./prep.sh"], stdout=of, stderr=of)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './prep.sh'

**Comment by pfandzelter** [comment]
I see, that should probably be `prep-simple.sh`. I fixed this now

**Comment by kadalihiranmayee** [comment]
Hii @pfandzelter! I hope you find this message well. Sorry for disturbing you again, I'm working on your paper for my thesis and need to run the experiment. I'm having some issue with the  the Docker image git.tu-berlin.de:5000/mcc-fred/fred/fred:v0.2.18 and git.tu-berlin.de:5000/mcc-fred/fred/alexandra:v0.2.18 cannot be found in the specified registry. I saw they just updated and I'm trying to update the image as well, but can you please look at the document and send me suggested updates as well please, it would be very helpful!
[preparation.txt](https://github.com/user-attachments/files/16228720/preparation.txt)
[4_movingaverage-10-1-300-10-1-25-100-1-10-cloud-2.txt](https://github.com/user-attachments/files/16228721/4_movingaverage-10-1-300-10-1-25-100-1-10-cloud-2.txt)

**Comment by pfandzelter** [comment]
I think you have the right idea, it might be easiest to update the image to "v0.2"
